### ISSUE TITLE
make fails

### ISSUE THREAD

**Issue by Ondjultomte** [hadfl/lxadm#13] opened 2017-09-28 20:44 UTC
root@omnios:~/lxadm-0.1.4# ./configure --prefix=/opt/lxadm-0.1.4 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... conftools/install-sh -c -d
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '0' is supported by ustar format... yes
checking whether GID '0' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether to enable maintainer-specific portions of Makefiles... no
checking whether make supports nested variables... (cached) yes
checking for perl... /usr/bin/perl
checking for curl... /usr/bin/curl
checking for wget... /usr/bin/wget
checking for pod2man... /usr/bin/pod2man
checking for perl version greater than or equal to 5.10.1... ok
checking for grep that handles long lines and -e... /usr/bin/ggrep
checking for gnumake... no
checking for gmake... no
checking for make... /usr/bin/make
checking for gnu make availablility... configure: error: GNU make not found. Try setting the GMAKE environment variable.
root@omnios:~/lxadm-0.1.4# make
make: Fatal error: No arguments to build
root@omnios:~/lxadm-0.1.4# make install
make: Fatal error: Don't know how to make target install
root@omnios:~/lxadm-0.1.4# make
make: Fatal error: No arguments to build
root@omnios:~/lxadm-0.1.4# make install
make: Fatal error: Don't know how to make target `install'

pastebin:
https://pastebin.com/1b6LeujX

**Comment by hadfl** [comment] 2017-09-28 21:04
try again using gnu make.

if not installed (on omnios): `pkg install developer/build/gnu-make`

then: 
```
./configure ...
gmake
gmake install
```

**Comment by hadfl** [comment] 2017-10-01 15:18
closing this since README was updated. Please re-open in case the issue is not resolved.

**Closed as completed by hadfl** 2017-10-01 15:18 UTC
